# Generated by Django 4.2.1 on 2023-05-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="workouts",
            new_name="workout",
        ),
        migrations.RenameModel(
            old_name="workout_plans",
            new_name="workout_plan",
        ),
    ]
