# Generated by Django 4.2.1 on 2023-05-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_rename_workouts_workout_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workout",
            old_name="wourkout_name",
            new_name="workout_name",
        ),
    ]
