# Generated by Django 4.2.1 on 2023-05-28 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_rename_wourkout_name_workout_workout_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="image",
            field=models.ImageField(default=django.utils.timezone.now, upload_to="img"),
            preserve_default=False,
        ),
    ]
