# Generated by Django 4.2.1 on 2023-05-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_workout_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workout_plan",
            old_name="wourkout_name",
            new_name="workout_name",
        ),
    ]
