# Generated by Django 4.2.1 on 2023-05-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_rename_wourkout_name_workout_plan_workout_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout_plan",
            name="username",
            field=models.CharField(max_length=128),
        ),
    ]
