# Generated by Django 4.2.1 on 2023-05-29 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_alter_workout_plan_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout_plan",
            name="progress",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
