# Generated by Django 4.2.1 on 2023-06-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_imagemodel_imcar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="workout_name",
            field=models.CharField(max_length=25, unique=True, verbose_name="workout"),
        ),
    ]
