# Generated by Django 4.2.1 on 2023-06-01 13:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_alter_workout_workout_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="workout_level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("image1", models.ImageField(upload_to="workout_images")),
                ("image2", models.ImageField(upload_to="workout_images")),
                ("image3", models.ImageField(upload_to="workout_images")),
                ("image4", models.ImageField(upload_to="workout_images")),
                (
                    "workout_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.workout",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="imcar",
            name="images",
        ),
        migrations.AlterField(
            model_name="workout_plan",
            name="progress",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.DeleteModel(
            name="ImageModel",
        ),
        migrations.DeleteModel(
            name="ImCar",
        ),
    ]
