# Generated by Django 4.2.1 on 2023-06-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0018_history_per_workout"),
    ]

    operations = [
        migrations.RenameField(
            model_name="history_per_workout",
            old_name="data",
            new_name="date",
        ),
    ]
